#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

puts "Hi group! Our compiler front-end should run here and return relevant exit code"
