#!/bin/bash
PATH0='test_suite/valid'
COMPILE='./compile'
VALID_CODE=0
INVALID_SYNTAX=100
INVALID_SEMANTIC=200
TTOTAL=0
TVALID=0
EXIT=0

compile_set() {
  TOTAL=0
  VALID=0
  CUR_PATH=$1
  REQ_CODE=$2
 # echo "Starting set $CUR_PATH"
  # shellcheck disable=SC2044
  for prog in $(find $CUR_PATH -name '*.wacc');
  do
    ((TOTAL+=1))
 #   echo "Compiling: $prog"
    $COMPILE -t "$prog"                       # Try to compile each program
    EXIT_CODE=$?
    if ((EXIT_CODE==REQ_CODE))
      then
     #   echo -e "   O Expected: $REQ_CODE Code: $EXIT_CODE $prog\n"
        ((VALID+=1))
      else
        echo -e "   X Expected: $REQ_CODE Code: $EXIT_CODE $prog\n"
    fi
    #echo "$VALID/$TOTAL in $CUR_PATH"
  done
  ((TTOTAL+=TOTAL))
  ((TVALID+=VALID))
}

# compile all sub-sets of programs that you want to test
PATH1="test_suite/*"
for SUBPATH in $PATH1
do
  compile_set "$SUBPATH" "$VALID_CODE"
done

exit 0

echo "$TVALID/$TTOTAL test passed!"
if((TVALID!=TTOTAL))
then
  echo "Compiler is not perfect yet :( (1)"
  exit 1
else
  echo "Compiler works as expected yay :( (0)"
  exit 0
fi