#!/bin/bash
VALID_BASIC='test_suite/valid/variables'
VALID_DIR='test_suite/valid'
INVALID_SEMANTIC_BASIC='test_suite/invalid/semanticErr/variables'
INVALID_SYNTAX_DIR='test_suite/invalid/syntaxErr'
INVALID_SEMANTIC_DIR='test_suite/invalid/semanticErr'
COMPILE='./compile'
VALID_CODE=0
INVALID_SYNTAX=100
# shellcheck disable=SC2034
INVALID_SEMANTIC=200
TTOTAL=0
TVALID=0

compile_set() {
  TOTAL=0
  VALID=0
  CUR_PATH=$1
  REQ_CODE=$2
  echo "Starting set $CUR_PATH"
  # shellcheck disable=SC2044
  for prog in $(find "$CUR_PATH" -name "*.wacc");
  do
    ((TOTAL+=1))
    echo "Compiling: $prog"
    $COMPILE "$prog"                       # Try to compile each program
    EXIT_CODE=$?
    if ((EXIT_CODE==REQ_CODE))
      then
        echo -e "   O Expected: $REQ_CODE Code: $EXIT_CODE $prog\n"
        ((VALID+=1))
      else
        echo -e "   X Expected: $REQ_CODE Code: $EXIT_CODE $prog\n"
    fi
    echo "$VALID/$TOTAL in $CUR_PATH"
  done
  ((TTOTAL+=TOTAL))
  ((TVALID+=VALID))
}

compile_parent_set(){
  PARENT=$1
  CODE=$2
  for SUBPATH in $PARENT
  do
    compile_set "$SUBPATH" "$CODE"
  done
}

#####################

# Actual testing calls

#####################


# compile all programs in the particular folder $1 and check for code $2
compile_set "$VALID_BASIC" "$VALID_CODE"
# compile_set "$INVALID_SYNTAX_DIR" "$INVALID_SYNTAX"
compile_set "$INVALID_SEMANTIC_BASIC" "$INVALID_SEMANTIC"

# compile all programs in the sub-folders (recursively) of $1 and check for code $2
# compile_parent_set "$PARENTPATH" "$INVALID_SYNTAX"

echo -e '\n=========='

echo "$TVALID/$TTOTAL test passed!"
if((TVALID!=TTOTAL))
then
  echo "Compiler is not perfect yet :( (1)"
  echo -e '=========='
  exit 1
else
  echo "Compiler works as expected yay : ) (0)"
  echo -e '=========='
  exit 0
fi
